project:
  type: book
  resources:
    - assets/**
  output-dir: docs

book:
  title: "Macroeconomics"
  author: "Your Name"
  site-url: "https://clb18.github.io/ECON_2010_Macroeconomics"
  repo-url: "https://github.com/clb18.github.io/ECON_2010_Macroeconomics"
  date: today
  search: true

  chapters:
    - index.qmd
    - syllabus.qmd
    - part: "Contents"
      chapters:
        - Contents/Chapter01.qmd
        # - Contents/Chapter02.qmd
        # - Contents/Chapter03.qmd
        # Add one line per chapter as you create them

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    number-sections: true
    css: styles.css
    grid:
      sidebar-width: 275px
      body-width: 1200px
      margin-width: 0px
      gutter-width: 1.5rem
  pdf:
    documentclass: scrreprt